blog/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('blogs/', views.PostListView.as_view(), name='blogs'),
    path('<int:pk>', views.PostDetailView.as_view(), name='post-detail'),
    path('bloggers/', views.AuthorListView.as_view(), name='bloggers'),
    path('blogger/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
    path('<int:pk>/create', views.CommentCreate.as_view(), name='comment'),
    path('create/', views.PostCreate.as_view(), name='post-create'),
]

diyblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('', RedirectView.as_view(url='/blog/', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=500, help_text='Введите описание автора:')

    class Meta:
        ordering = ['user', 'summary']
    
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.user.id)])
    
    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=70, verbose_name='Заголовок')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = models.TextField(max_length=2000, help_text='Введите текст поста', verbose_name='Содержание')
    date_of_post = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['date_of_post', 'title']
        verbose_name = 'Публикация'

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.id)])
    
    def __str__(self):
        return '{0}'.format(self.title, self.date_of_post)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.TextField(max_length=1000, help_text='Введите комментарий', verbose_name='Комментарий')
    time_of_comment = models.DateTimeField(auto_now_add=True, verbose_name='Дата комментария')

    class Meta:
        ordering = ['time_of_comment']
        verbose_name = 'Комментарий'

    def get_absolute_url(self):
        return reverse('post-detail', args=[str(self.post.id)])

    def __str__(self):
        return '{0}: {1}. Time: {2}'.format(self.author.username, self.post.title, self.time_of_comment)

blog/views.py
from django.shortcuts import render
from .models import Author, Post, User, Comment
from datetime import date
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django.forms import forms


def index(request):
    num_of_authors = User.objects.all().count()
    num_of_posts = Post.objects.all().count()

    num_today_posts = Post.objects.filter(date_of_post=date.today()).count()
    num_today_comms = Comment.objects.filter(time_of_comment__date=date.today()).count()

    return render(
        request, 'index.html',
        context={
            'num_of_authors': num_of_authors,
            'num_of_posts': num_of_posts,
            'num_today_posts': num_today_posts,
            'num_today_comms': num_today_comms,
            }
        )


class PostListView(generic.ListView):
    model = Post
    paginate_by = 5

    def get_queryset(self):
        return Post.objects.order_by('-date_of_post').all()

class PostDetailView(generic.DetailView):
    model = Post

class PostCreate(LoginRequiredMixin, generic.edit.CreateView):
    model = Post
    fields = ['title', 'description']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(PostCreate, self).form_valid(form)


class AuthorListView(generic.ListView):
    model = Author

class AuthorDetailView(generic.DetailView):
    model = Author


class CommentCreate(LoginRequiredMixin ,generic.edit.CreateView):
    model = Comment
    fields = ['comment_text']

    def get_context_data(self, **kwargs):
        context = super(CommentCreate, self).get_context_data(**kwargs)
        context['post'] = get_object_or_404(Post, pk=self.kwargs['pk'])
        return context
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return super(CommentCreate, self).form_valid(form)
    

blog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>

  {% block title %}<title>DIY Блог</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">
    <p></p>
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Домашняя страница</a></li>
          <li><a href="{% url 'bloggers' %}">Все авторы</a></li>
          <li><a href="{% url 'blogs' %}">Все блоги</a></li>
          <p>&nbsp;</p>
          {% if user.is_authenticated %}
            <p>Пользователь: {{ user.get_username }}</p>
            <p><a href="{% url 'logout' %}?next={{request.path}}">Выйти</a></p>
            <hr>
            <p><a href="{% url 'post-create' %}">Создать публикацию</a></p>
          {% else %}
            <p><a href="{% url 'login' %}?next={{request.path}}">Войти</a></p>
          {% endif %}
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}

      {% block pagination %}
        {% if is_paginated %}
            <div class="pagination">
                <span class="page-links">
                    {% if page_obj.has_previous %}
                        <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                    {% endif %}
                    <span class="page-current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">Следующая</a>
                    {% endif %}
                </span>
            </div>
        {% endif %}
      {% endblock %}
      
      </div>
    </div>

  </div>
</body>
</html>

blog/templates/blog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Автор {{ author.user.username }}</h1>

  <h3> Описание </h3>
  <p> {{ author.summary }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4> Публикации: </h4>

    {% if author.user.post_set.all %}
      {% for post in author.user.post_set.all %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{ post.date_of_post }})
      </li>
      {% endfor %}
    {% else %}
      <p>Публикации отсутствуют</p>
    {% endif %}
  </div>
{% endblock %}

blog/templates/blog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Авторы</h1>

    {% if author_list %}
    <ul>

      {% for author in author_list %}
      <li>
        <a href="{{ author.get_absolute_url }}">{{ author.user.username }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p> Авторов нет.</p>
    {% endif %}
{% endblock %}

blog/templates/blog/comment_form.html
{% extends "base_generic.html" %}

{% block content %}
<p>Комментарий для публикации: <a href="{% url 'post-detail' post.pk %}">{{post.title}}</a></p>

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Добавить" />
    
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>{{ post.title }}</h1>

  <p><strong>Дата поста:</strong> {{ post.date_of_post }}</p>
  <p><strong>Автор:</strong> <a href="{{ post.author.author.get_absolute_url }} ">{{ post.author }}</a></p>
  <p></p>
  <p>{{ post.description }}</p>

  <div style="margin-left:20px;margin-top:20px">

    <h4>Комментарии</h4>

    {% for comment in post.comment_set.all %}
    <hr>
    <p>{{ comment.author }} ({{ comment.time_of_comment }}) - {{ comment.comment_text }}</p>
    {% endfor %}
    <hr>
    {% if user.is_authenticated %}
      <a href="{% url 'comment' post.id %}">Добавить комментарий</a></p>
    {% else %}
      <p><a href="{% url 'login'%}?next={{request.path}}">Войти</a> чтобы добавить комментарий</p>
    {% endif %} 
  </div>
{% endblock %}

blog/templates/blog/post_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Создать публикацию" />
    
</form>
{% endblock %}

blog/templates/blog/post_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Список постов</h1>

    {% if post_list %}
    <ul>

      {% for post in post_list %}
      <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a> ({{ post.date_of_post }}) — <a href="{{ post.author.author.get_absolute_url }}">{{ post.author }}</a>
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Постов нет.</p>
    {% endif %}
{% endblock %}

blog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Домашняя страница блога</h1>

<h2>Информация</h2>

  <p>Статистика сайта:</p>
  <ul>
    <li><strong>Количество авторов на сайте:</strong> {{ num_of_authors }}</li>
    <li><strong>Общее количество постов:</strong> {{ num_of_posts }}</li>
    <p></p>
    <li><strong>Постов за сегодня:</strong> {{ num_today_posts }}</li>
    <li><strong>Комментариев за сегодня:</strong> {{ num_today_comms }}</li>
  </ul>

{% endblock %}